name: Deploy Shopping List to Hetzner VPS

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Hetzner VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT || 22 }}
        script: |
          # Navigate to app directory
          cd /var/www/html/shopping-list-app

          # Pull latest changes
          git fetch origin
          git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)

          # Set proper permissions
          chmod -R 755 /var/www/html/shopping-list-app

          echo "✅ Shopping List deployment completed successfully"